version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - API_SECRET_KEY=${API_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_URL_BUCKET=${S3_URL_BUCKET}
    volumes:
      - ./models:/app/models
      - ./assets:/app/assets
    depends_on:
      - redis
    ports:
      - "8000:8000"
  worker:
    build: .
    command: celery -A backend.tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - API_SECRET_KEY=${API_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_URL_BUCKET=${S3_URL_BUCKET}
    volumes:
      - ./models:/app/models
      - ./assets:/app/assets
    depends_on:
      - redis
