version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "8000:8000"
  worker:
    build: .
    command: celery -A backend.tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - redis
